### PR TITLE
Dependencies

### LINKED ISSUE #5: Remove JobScheduler singleton
Is there a reason other than convenience that JobScheduler produces a singleton?

`Instance` isn't referenced anywhere in the code except for `IJobExtensions.Schedule()`, which is just a convenience method to avoid `scheduler.Schedule(job)`. It doesn't even allow the client to avoid keeping a reference to the scheduler or referencing the instance themself, because they still need to call `scheduler.Flush()` and `scheduler.Dispose()` neither of which which have an extension method (and no extension method would make sense).

It seems to me it adds complexity, testing issues, and lack of thread safety.

Imagine the following...

```
var scheduler1 = new JobScheduler(...);

// somewhere completely else, or on a different thread:
var scheduler2 = new JobScheduler(...);
scheduler2.Dispose();

myJob.Schedule(...); // schedules on an invalid, disposed JobScheduler, even if you might expect the first!
```

I would argue we remove the `Instance` and instead let the user track their own singleton instead, if they wish. If that sounds OK, let me know, and I can make a PR!

### LINKED ISSUE #6: `JobScheduler` never really quits.
It has a problem where it doesn't clean up the worker threads and thus stopping the application from shutting down properly. Even if dispose is called on the scheduler, the application never quits. The work-around for now is to just call Environment.Exit(0) after everything has closed.

### PR DESCRIPTION
**Pull request by LilithSilver**
Apologies for the giant PR, but I didn't want to pollute the repo with too many incremental changes, since this changes how the system works on a pretty fundamental level.

Let's begin...

## Public API changes

- `JobScheduler.Schedule` now takes an optional `JobHandle` dependency to set-up a single job that must `Complete()` before the job can execute
- Adds `JobScheduler.CombineDependecies(JobHandles[] handles)`, which schedules a `JobHandle` that can only complete once all the provided `handles` have individually completed.
	+ The array is allocated by the client, and can be reused, ***as long as*** it is only touched by the client once `Complete()` is called on the `JobHandle` (or one of its dependencies). Other behavior is undefined. (For example, in a game, it could be reused the next frame, if the job is completed later on the current frame.)
- Removes pool-on-complete jobs (set-and-forget API)
	+ The new system automatically returns Job resources regardless of whether they're in-progress, so you can just set-and-forget any job without calling Complete()
	+ `JobScheduler.Schedule` no longer takes a `poolOnComplete`
	+ Removes `JobHandle.Return`
- `JobScheduler.Dispose` actually quits threads now (fixes #6)
- Removes `JobScheduler.Instance` (fixes #5)
- Can no longer `JobScheduler.Schedule` or `JobScheduler.Flush` from threads other than the main thread `JobScheduler` was instantiated on.
	+ You _shouldn't_ have done that before, but technically it would do something. Now you can't.
- Removes `IJob.Schedule` in favor of `JobScheduler.Schedule`
- Changes `JobHandle.Complete` to `JobHandle.CompleteAll` for clarity

## Tests
- Adds a ton of tests
	+ All tests that inherit from `SchedulerFixture` now run for all common thread configurations (default, 1, 2, 4, 8, 16)
- Organizes the test directory a bit

Let me know if you can think of more tests to run.

## Documentation

- Updated README.md with the new API

## `JobScheduler` implementation notes
The class now uses a custom `JobInfoPool` to handle job tracking.

+ Per each produced `JobHandle`, it stores a `Dictionary` storing a struct with...
	* A unique ID
	* A list of dependencies/a single dependency
	* The `ManualResetEvent` for the job
+ When a job's thread runs...
	* It asks the `JobInfoPool` for the job's dependencies, and then runs `Complete` on each dependency. Because jobs are queued in the FIFO order they're scheduled, dependencies are guaranteed to run before dependants. At worst, there might be a few threads waiting for one thread to complete, because those threads depend on the first thread, even while there's valid work to complete later down on the queue.
		- This could be mitigated by sorting the list by dependancy counts in `Flush()` prior to dispatching the jobs to the `ConcurrentQueue`. This strategy wouldn't help if the user was frequently calling `Flush()`, however.
		- A work-stealing implementation would completely prevent this issue!
	* The thread does its work, if present.
	* The thread tells `JobInfoPool` to recycle the entry. If someone has subscribed with `Complete`, it uses a separate dictionary to avoid returning the WaitHandle too early. Otherwise, it returns the WaitHandle to the pool and clears the dictionary entry, marking the task as officially complete.
+ When Complete is called, it first checks `JobInfoPool` for the `JobHandle`'s ID.
	* If the ID is still present in the dictionary, it assumes the job is still in flight, tells `JobInfoPool` that it has subscribed to the `WaitHandle`, and calls a `ManualResetEvent.WaitOne()`.
	* If the ID isn't in the dictionary, it assumes the job has been completed already, and returns.

`JobScheduler` uses more locks than I would prefer (for `JobInfoPool`), but I don't think there's an interlocked solution here. I'm not sure how much they impact performance, here, but I've optimized and atomized them as best I can. Let me know if you have any ideas. One note is that C#'s R/W locks all allocate seemingly randomly so we have to use normal locks.

## Questions/notes

Mostly for @genaray...

- Do you know of a good way to benchmark the scheduler? I'd like to get an idea of how bad the additional job creation overhead is. That said, I don't know what a good expected value would even be.
- If you're OK with either adding external assemblies, or copying some code over, [this package](https://github.com/Wsm2110/Faster.Map) could help with the `Dictionary`
	+ It would let us control allocations much more discretely instead of `Dictionary`'s hash-miss behavior that can infrequently allocate (but still only on `Schedule`).
- I'm pretty inexperienced in parallel programming, so let me know if there are better ways of doing what I'm doing/potential oversights I missed.

### CODE REVIEW

**Comment by genaray** [comment]
Thanks first! :) 
I took a quick look. So JobInfoPool is now responsible for pooling, correct? Uses some dictionaries though.

I think even the dictionaries could be used bluntly by normal arrays. The job id is simply incrementel, correct? In this case you could just store it in a lookup array which would make the access much faster :) 

Another question, why does JobInfo exist as a struct at all? Couldn't you store the dependencies directly in the normal job-struct and pool them from there? ^^ 

But great work, that was fast :)

**Comment by LilithSilver** [comment]
> I took a quick look. So JobInfoPool is now responsible for pooling, correct? Uses some dictionaries though.

Yep! And yeah, not a fan of the dictionaries but they haven't caused unexpected allocation from my initial testing.

The alternative is something like this: https://github.com/Wsm2110/Faster.Map We could either add a package reference, or alternatively just copy over the class (it's MIT licensed).


> I think even the dictionaries could be used bluntly by normal arrays. The job id is simply incrementel, correct? In this case you could just store it in a lookup array which would make the access much faster :)

I couldn't think of a way to implement a normal array lookup. The issue is that, the lookup array would end up having holes in it. For example, if we assigned jobs 0, 1, 2, 3, and 1 and 2 complete first, the array is now 0, _, _, 3, and we can't reuse those two slots until 0 is gone and we can shift over everything in the array so that it looks like 3, 4, 5, 6. 

But let me know if I'm missing something. I would LOVE a lookup array-based solution, I just haven't thought of one that will only alloc for the handles currently in-progress.

> Another question, why does JobInfo exist as a struct at all? Couldn't you store the dependencies directly in the normal job-struct and pool them from there? ^^

`JobInfoPool` works on the idea that once a job has disappeared, it is assumed complete. To check dependencies we need to do a lot of "is this job complete?" checks. 

If we used the existing JobMeta, we'd have to search through both the job queue and the work queue every single time we wanted to check if a job was complete. This would cause interlock issues and if we later implement work stealing it would get crazy!

**Comment by genaray** [comment]
> > I think even the dictionaries could be used bluntly by normal arrays. The job id is simply incrementel, correct? In this case you could just store it in a lookup array which would make the access much faster :)
> 
> I couldn't think of a way to implement a normal array lookup. The issue is that, the lookup array would end up having holes in it. For example, if we assigned jobs 0, 1, 2, 3, and 1 and 2 complete first, the array is now 0, _, _, 3, and we can't reuse those two slots until 0 is gone and we can shift over everything in the array so that it looks like 3, 4, 5, 6.
> 
> But let me know if I'm missing something. I would LOVE a lookup array-based solution, I just haven't thought of one that will only alloc for the handles currently in-progress.


Well we could recycle the ids once their job completed. We could simply use a `ConcurrentQueue`. 
However, we would need to ensure that recycled ids only enter the queue once their whole depdency-stack completed. So we would need some sort of intermediate Queue that stores the ids until the dependency resolved. For every potential job.
`ConcurrentQueue<int>[] resolvedDependencies;  var resolvedDependencies = resolved...[jobId];`

I hope the id is understandable, but we could recycle the job-ids... first we store completed jobids till the whole tree completed and then we flush them to the pool for being reused. This way we ensure that there no deadlocks and no holes in the array (just temporary ones) ^^ 

> If we used the existing JobMeta, we'd have to search through both the job queue and the work queue every single time we wanted to check if a job was complete. This would cause interlock issues and if we later implement work stealing it would get crazy!

Hmm... really? E.g. if every JobHandle looks like this: `struct JobHandle{ Id, ResetEvent, JobHandle[] (Or int[]?) Dependencies, Completed..}` we could just iterate the tree to see which job already finished and which not. Its basically a unification of the JobHandle and the JobInfo structs. And well that one could get checked directly without accessing the infopool multiple times. But probably I'm missing something here ^^

**Comment by LilithSilver** [comment]
> Well we could recycle the ids once their job completed. We could simply use a ConcurrentQueue.
However, we would need to ensure that recycled ids only enter the queue once their whole depdency-stack completed. So we would need some sort of intermediate Queue that stores the ids until the dependency resolved. For every potential job.
ConcurrentQueue<int>[] resolvedDependencies;  var resolvedDependencies = resolved...[jobId];

> I hope the id is understandable, but we could recycle the job-ids... first we store completed jobids till the whole tree completed and then we flush them to the pool for being reused. This way we ensure that there no deadlocks and no holes in the array (just temporary ones) ^^

I think I understand what you mean, but how would we ensure that the user can `Complete()` any handle, even one that has already been re-pooled? 

For example... 

```
var handle1 = Scheduler.Schedule(job1);
Scheduler.Flush();
// job1 is short lived and completes immediately, so its jobId is recycled
var handle2 = Scheduler.Schedule(job2); // takes job1's ID
Scheduler.Flush();

handle1.Complete(); // will actually complete handle2 because it recycled the ID!
```

(This solution would also cause more allocation pressure, since we have to store the full dependency tree even when jobs are totally completed, but I think that's less of an issue here than the completion issue.)

> Hmm... really? E.g. if every JobHandle looks like this: struct JobHandle{ Id, ResetEvent, JobHandle[] (Or int[]?) Dependencies, Completed..} we could just iterate the tree to see which job already finished and which not. Its basically a unification of the JobHandle and the JobInfo structs. And well that one could get checked directly without accessing the infopool multiple times. But probably I'm missing something here ^^

You're right, I think, about the dependencies!

If `JobMeta` stored the dependencies instead of `JobInfo`, we could avoid a lock on `JobScheduler.cs:80`.  We would still need to grab the info for job completion and scheduling, of course, as above. But this would make it simpler and faster! I've pushed a couple commits that should improve that, and reduce a couple other cases of locking the pool as well.

However, I think it's still more effective to have a separate `JobInfo`, which stores `WaitHandle`, that exists in the pool, rather than just a `JobHandle`. The reason for this is just from a code standpoint. If we're storing `JobHandle` but also getting the handle back from the user, we can never actually trust that the user has an updated handle, because it's a struct. We can't check things like `WaitHandle` or `Completed` because we have to acquire the newest data from the pool anyways, because threads might've done work in the meantime. So why are we giving that data to the user in the first place, and making the `JobHandle` heavier to pass around for the user? Since we have to access the info pool anyways to mark a handle complete, or to check its completion status, which with the above change is all we really use the info pool for.

**Comment by LilithSilver** [comment]
Out of curiosity, I left some benchmarks running between `Dictionary` and `FastMap` from that one package. They both turned out roughly the same, so I don't think it matters outside of perhaps allocation-friendliness (unless we can get an array solution up and running of course).

Interestingly, however, both benchmarks turned out mostly faster than before this PR (in the non-alloc case of course; the alloc case is a standing bug). I'm not at all sure why, since I only added overhead...?

Anyways, if we get an array solution going, I'm happy to try and benchmark it.

Before this PR (see #8):

| Method              | Threads | ExcludeFirstWave | ConcurrentJobs | Waves | Mean        | Error    | StdDev   | Gen0      | Gen1      | Allocated  |
|-------------------- |-------- |----------------- |--------------- |------ |------------:|---------:|---------:|----------:|----------:|-----------:|
| **BenchmarkParallel**   | **0**       | **True**             | **32**             | **10240** |    **343.2 ms** |  **4.13 ms** |  **3.66 ms** |         **-** |         **-** |      **600 B** |
| BenchmarkSequential | 0       | True             | 32             | 10240 |  3,732.7 ms | 17.31 ms | 16.19 ms |         - |         - |      600 B |
| **BenchmarkParallel**   | **0**       | **True**             | **128**            | **10240** |  **1,344.9 ms** | **11.85 ms** | **11.09 ms** | **1000.0000** | **1000.0000** | **54921816 B** |
| BenchmarkSequential | 0       | True             | 128            | 10240 | 14,916.6 ms | 97.26 ms | 81.22 ms |         - |         - |      600 B |



This PR with Dictionary:

| Method                | Threads | ExcludeFirstWave | ConcurrentJobs | Waves | Mean        | Error    | StdDev   | Gen0      | Gen1      | Allocated  |
|---------------------- |-------- |----------------- |--------------- |------ |------------:|---------:|---------:|----------:|----------:|-----------:|
| **BenchmarkParallel**     | **0**       | **True**             | **32**             | **10240** |    **263.6 ms** |  **1.45 ms** |  **1.36 ms** |         **-** |         **-** |      **600 B** |
| BenchmarkSequential   | 0       | True             | 32             | 10240 |  3,573.0 ms |  8.12 ms |  7.20 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 32             | 10240 |  1,258.1 ms | 20.49 ms | 19.16 ms |         - |         - |      600 B |
| **BenchmarkParallel**     | **0**       | **True**             | **128**            | **10240** |  **1,858.2 ms** | **19.16 ms** | **17.92 ms** | **1000.0000** | **1000.0000** | **54900312 B** |
| BenchmarkSequential   | 0       | True             | 128            | 10240 | 14,192.5 ms | 29.57 ms | 26.21 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 128            | 10240 |  7,471.6 ms | 33.29 ms | 29.51 ms | 1000.0000 | 1000.0000 | 54911064 B |


This PR with FastMap:

| Method                | Threads | ExcludeFirstWave | ConcurrentJobs | Waves | Mean        | Error    | StdDev   | Gen0      | Gen1      | Allocated  |
|---------------------- |-------- |----------------- |--------------- |------ |------------:|---------:|---------:|----------:|----------:|-----------:|
| **BenchmarkParallel**     | **0**       | **True**             | **32**             | **10240** |    **254.6 ms** |  **2.65 ms** |  **2.48 ms** |         **-** |         **-** |      **600 B** |
| BenchmarkSequential   | 0       | True             | 32             | 10240 |  3,569.3 ms | 18.08 ms | 16.91 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 32             | 10240 |  1,275.3 ms | 14.67 ms | 13.72 ms |         - |         - |      600 B |
| **BenchmarkParallel**     | **0**       | **True**             | **128**            | **10240** |  **1,751.5 ms** | **25.95 ms** | **24.27 ms** | **1000.0000** | **1000.0000** | **54927192 B** |
| BenchmarkSequential   | 0       | True             | 128            | 10240 | 14,326.0 ms | 77.32 ms | 72.33 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 128            | 10240 |  7,307.8 ms | 21.66 ms | 20.26 ms | 1000.0000 | 1000.0000 | 54921816 B |

**Comment by genaray** [comment]
> I think I understand what you mean, but how would we ensure that the user can `Complete()` any handle, even one that has already been re-pooled?
> 
> For example...
> 
> ```
> var handle1 = Scheduler.Schedule(job1);
> Scheduler.Flush();
> // job1 is short lived and completes immediately, so its jobId is recycled
> var handle2 = Scheduler.Schedule(job2); // takes job1's ID
> Scheduler.Flush();
> 
> handle1.Complete(); // will actually complete handle2 because it recycled the ID!
> ```

Hmmm well... that's right. We would need to tolerate this behaviour. We could however add an version to it. Like when its recycled, its version gets increased and the id is being recycled. Like we do in Arch for entities :) This way we could check if its the original or a recycled one.

> However, I think it's still more effective to have a separate `JobInfo`, which stores `WaitHandle`, that exists in the pool, rather than just a `JobHandle`. The reason for this is just from a code standpoint. If we're storing `JobHandle` but also getting the handle back from the user, we can never actually trust that the user has an updated handle, because it's a struct.

Well that's right. This way its hidden from the user which can avoid potential risks and bugs ^^



> Interestingly, however, both benchmarks turned out mostly faster than before this PR (in the non-alloc case of course; the alloc case is a standing bug). I'm not at all sure why, since I only added overhead...?

Wait what? The pr is faster than the master which did not had dependencies ? :o 
I need to look at the commits again, but you have not changed the way the jobs are being dequeued or? Weird but that's actually pretty good ^^

**Comment by LilithSilver** [comment]
> Hmmm well... that's right. We would need to tolerate this behaviour. We could however add an version to it. Like when its recycled, its version gets increased and the id is being recycled. Like we do in Arch for entities :) This way we could check if its the original or a recycled one.

Ah right, that is a solution! I'll set up an implementation and benchmark it, just to make sure it's still faster than Robin Hood hashing with the additional Queue overhead. But it should be, I think. Thanks!

**Comment by LilithSilver** [comment]
Okay, here are the results.....

New Array implementation with versions:

| Method                | Threads | ExcludeFirstWave | ConcurrentJobs | Waves | Mean        | Error     | StdDev    | Gen0      | Gen1      | Allocated  |
|---------------------- |-------- |----------------- |--------------- |------ |------------:|----------:|----------:|----------:|----------:|-----------:|
| **BenchmarkParallel**     | **0**       | **True**             | **32**             | **10240** |    **259.6 ms** |   **3.35 ms** |   **3.13 ms** |         **-** |         **-** |      **600 B** |
| BenchmarkSequential   | 0       | True             | 32             | 10240 |  3,588.9 ms |  11.53 ms |  10.78 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 32             | 10240 |  1,356.6 ms |   9.58 ms |   8.96 ms |         - |         - |      600 B |
| **BenchmarkParallel**     | **0**       | **True**             | **128**            | **10240** |  **1,824.4 ms** |  **28.19 ms** |  **26.37 ms** | **1000.0000** | **1000.0000** | **54927192 B** |
| BenchmarkSequential   | 0       | True             | 128            | 10240 | 15,500.4 ms | 301.39 ms | 347.08 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 128            | 10240 |  7,500.9 ms |  32.37 ms |  30.28 ms | 1000.0000 | 1000.0000 | 54873432 B |

Fastmap robin-hood implementation:
| Method                | Threads | ExcludeFirstWave | ConcurrentJobs | Waves | Mean        | Error    | StdDev   | Gen0      | Gen1      | Allocated  |
|---------------------- |-------- |----------------- |--------------- |------ |------------:|---------:|---------:|----------:|----------:|-----------:|
| **BenchmarkParallel**     | **0**       | **True**             | **32**             | **10240** |    **257.8 ms** |  **1.65 ms** |  **1.55 ms** |         **-** |         **-** |      **600 B** |
| BenchmarkSequential   | 0       | True             | 32             | 10240 |  3,594.9 ms | 30.81 ms | 27.31 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 32             | 10240 |  1,294.6 ms |  8.37 ms |  7.83 ms |         - |         - |      600 B |
| **BenchmarkParallel**     | **0**       | **True**             | **128**            | **10240** |  **1,792.7 ms** | **23.29 ms** | **21.79 ms** | **1000.0000** | **1000.0000** | **54921816 B** |
| BenchmarkSequential   | 0       | True             | 128            | 10240 | 14,588.9 ms | 85.03 ms | 79.54 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 128            | 10240 |  7,362.2 ms | 23.99 ms | 22.44 ms | 1000.0000 | 1000.0000 | 54916440 B |

Dictionary (current)

| Method                | Threads | ExcludeFirstWave | ConcurrentJobs | Waves | Mean        | Error    | StdDev   | Gen0      | Gen1      | Allocated  |
|---------------------- |-------- |----------------- |--------------- |------ |------------:|---------:|---------:|----------:|----------:|-----------:|
| **BenchmarkParallel**     | **0**       | **True**             | **32**             | **10240** |    **265.4 ms** |  **0.96 ms** |  **0.89 ms** |         **-** |         **-** |      **600 B** |
| BenchmarkSequential   | 0       | True             | 32             | 10240 |  3,604.4 ms | 28.58 ms | 26.74 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 32             | 10240 |  1,379.9 ms | 12.51 ms | 11.70 ms |         - |         - |      600 B |
| **BenchmarkParallel**     | **0**       | **True**             | **128**            | **10240** |  **1,874.0 ms** | **21.40 ms** | **20.01 ms** | **1000.0000** | **1000.0000** | **54927192 B** |
| BenchmarkSequential   | 0       | True             | 128            | 10240 | 15,699.6 ms | 48.41 ms | 40.42 ms |         - |         - |      600 B |
| BenchmarkDependancies | 0       | True             | 128            | 10240 |  7,479.4 ms | 15.48 ms | 12.93 ms | 1000.0000 | 1000.0000 | 54916440 B |


So the results are:

- Array is definitely better than Dictionary
- FastMap is slightly better than Array (probably due to less overhead of struct re-insertion and version tracking, but the difference is negligible)

I'm loosely in favour of the FastMap implementation, because the code makes more sense to me (version tracking gets a bit weird). But other than that I don't mind either way; it's totally up to you.

Here are the two implementations:

[Using FastMap](https://github.com/LilithSilver/ZeroAllocJobScheduler/tree/dependencies-refactor-fastmap); faster and cleaner IMO but requires an external class poached from FasterMap and converted to netstandard
[Using Array with version tracking and JobID reuse](https://github.com/LilithSilver/ZeroAllocJobScheduler/tree/dependencies-refactor-versions); slightly slower and more complicated but no code bloat

So let me know which one is ideal and I'll clean it up and merge it into the branch.

**Comment by genaray** [comment]
Thanks first! I do not understand with my best will why the array implementation is a few ns slower. An array access is always faster than a dictionary access because no hashcode needs to be computed and there is less code overhead. This is really strange :O

I would even just say that we take the array variant, which is 2 ns slower, but that doesn't matter.

**Comment by LilithSilver** [comment]
I think it's because FastMap is just an underlying array: because it only uses ints, it doesn't have to compute a hash value (the hash value of an int is just the int). Then, with the Robin hood hashing, it's a good enough implementation that resolving the hash is slightly faster than version tracking!

But yeah, at this point it doesn't matter at all. These are micro-optimizations. I'll merge in the array variant!

**Comment by genaray** [comment]
> I think it's because FastMap is just an underlying array: because it only uses ints, it doesn't have to compute a hash value (the hash value of an int is just the int). Then, with the Robin hood hashing, it's a good enough implementation that resolving the hash is slightly faster than version tracking!
> 
> But yeah, at this point it doesn't matter at all. These are micro-optimizations. I'll merge in the array variant!

That's definitely interesting ^^ Okay, when it's done I'll definitely merge it! 
Thanks again, dependencies were on the todo list for a long time ^^

**Comment by genaray** [comment]
> Should be merged in already!

So its merged and refactored now! :) 
Could you take a look at it again to verify that everything still works as intended? 
I ran the tests and 1 or 2 of them failed. Not sure if that's due to my refactoring... however i did not change the code much. I replaced the list by an array and changed the way it recycles the versions slightly to improve code readability.

**Comment by LilithSilver** [comment]
I'll check! 

Were they the allocation tests? There's some instabilities in those that I'm addressing soon.

**Comment by LilithSilver** [comment]
All the tests run on my end in Debug configuration. There is one issue with JobSchedulerTests.cs:47 in Release mode:

```
    [Test]
    public void CannotAwaitUnflushedHandle()
    {
        var job = new SleepJob(0);
        var handle = Scheduler.Schedule(job);
        Assert.That(handle.Complete, Throws.InvalidOperationException);
    }

```
This condition is only checked in the debug configuration so it needs to have include guards like so or the test will run forever:

```
#if DEBUG
    [Test]
    public void CannotAwaitUnflushedHandle()
    {
        var job = new SleepJob(0);
        var handle = Scheduler.Schedule(job);
        Assert.That(handle.Complete, Throws.InvalidOperationException);
    }
#endif
```

But all other tests ran fine.

**Comment by genaray** [comment]
> #if DEBUG
>     [Test]
>     public void CannotAwaitUnflushedHandle()
>     {
>         var job = new SleepJob(0);
>         var handle = Scheduler.Schedule(job);
>         Assert.That(handle.Complete, Throws.InvalidOperationException);
>     }
> #endif

That fixed the JobScheduler test! Thanks! :) 
CombineDependencies also fails: 
image

Thats basically the last one failing ^^

**Comment by LilithSilver** [comment]
Hmm! That's not happening on my end. Does running `dotnet test` from the sln directory work instead of the IDE? And just checking, we're both at commit 8fe4ad83a881d882c7eb8b85bccc93d834257782?

If not it might be a processor-specific thing you'll have to debug.

> EDIT: I wonder if we can also pool JobMeta.Dependencies since it may be expensive for the user... or is that nonsense?

That would be really nice; I thought of a few options but decided it would be best to skip that complexity for a first pass. I'll make an issue for it.

**Comment by genaray** [comment]
> Hmm! That's not happening on my end. Does running `dotnet test` from the sln directory work instead of the IDE? And just checking, we're both at commit [8fe4ad8](https://github.com/genaray/ZeroAllocJobScheduler/commit/8fe4ad83a881d882c7eb8b85bccc93d834257782)? (Edit: The more-recent [644e07c](https://github.com/genaray/ZeroAllocJobScheduler/commit/644e07c9a7cdd7a72dbc4bb80687cd34cbc44e36) works for me too)

Yep we are on the same commit, ill try running it later again ^^

**Comment by LilithSilver** [comment]
@genaray Looking at the test for unrelated reasons, but: does increasing the number on CombineDependenciesTests:85 prevent the test failure for you? It's possible your main thread is hanging more than mine does.

**Pull request merged**
